apiVersion: v1
kind: ConfigMap
metadata:
  name: cms-labs-terminal-config
  namespace: $NAME
  labels:
    cms-labs.io/terminal-config: "true"
data:
  config.yaml: |-
    targets:
      - name: pc1
        label: PC1 · Sender
        mode: exec
        command: [/bin/sh]
      - name: sw1
        label: SW1 · Linux Bridge
        mode: exec
        command: [/bin/sh]
      - name: pc2
        label: PC2 · Destination
        mode: exec
        command: [/bin/sh]
      - name: pc3
        label: PC3 · Observer
        mode: exec
        command: [/bin/sh]
